type Item = {
  id: number;
  img: string;
  link: string;
  title: string;
  description: string;
  type: string;
};

export const bootCampList: Item[] = [
  {
    id: 9,
    img: "",
    link: "https://www.codestates.com/",
    title: "코드스테이츠",
    description: "",
    type: "",
  },
  {
    id: 10,
    img: "",
    link: "https://wecode.co.kr/",
    title: "위코드",
    description: "",
    type: "",
  },
  {
    id: 11,
    img: "",
    link: "https://www.vanillacoding.co/",
    title: "바닐라코딩",
    description: "",
    type: "",
  },
  {
    id: 12,
    img: "",
    link: "https://teamnova.co.kr/",
    title: "팀노바",
    description: "",
    type: "",
  },
  {
    id: 13,
    img: "",
    link: "https://codesquad.kr/",
    title: "코드스쿼드",
    description: "",
    type: "",
  },
  {
    id: 14,
    img: "",
    link: "https://www.codesoom.com/",
    title: "코드숨",
    description: "",
    type: "",
  },
  {
    id: 15,
    img: "",
    link: "https://www.fastcampus.co.kr/",
    title: "패스트캠퍼스",
    description: "",
    type: "",
  },
];

export const lectureList: Item[] = [
  {
    id: 1,
    img: "",
    link: "https://nomadcoders.co/",
    title: "노마드코더",
    description: "",
    type: "",
  },
  {
    id: 2,
    img: "",
    link: "https://www.inflearn.com/",
    title: "인프런",
    description: "",
    type: "",
  },
  {
    id: 3,
    img: "",
    link: "https://opentutorials.org/course/1",
    title: "생활코딩",
    description: "",
    type: "",
  },
  {
    id: 4,
    img: "",
    link: "https://www.udemy.com/ko/",
    title: "유데미",
    description: "",
    type: "",
  },
  {
    id: 5,
    img: "",
    link: "https://programmers.co.kr/",
    title: "프로그래머스",
    description: "",
    type: "",
  },
  {
    id: 6,
    img: "",
    link: "https://edu.goorm.io/",
    title: "구름EDU",
    description: "",
    type: "",
  },
  {
    id: 7,
    img: "",
    link: "https://www.codeit.kr/",
    title: "코드잇",
    description: "",
    type: "",
  },
  {
    id: 8,
    img: "",
    link: "https://www.edwith.org/",
    title: "edwith",
    description: "",
    type: "",
  },
];

export const blogList: Item[] = [
  {
    id: 1,
    img: "",
    link: "https://www.ridicorp.com/blog/",
    title: "리디북스",
    description: "",
    type: "company",
  },
  {
    id: 2,
    img: "",
    link: "https://d2.naver.com/home",
    title: "네이버",
    description: "",
    type: "company",
  },
  {
    id: 3,
    img: "",
    link: "https://tech.lezhin.com/",
    title: "레진코믹스",
    description: "",
    type: "company",
  },
  {
    id: 4,
    img: "",
    link: "https://engineering.linecorp.com/ko/blog/",
    title: "LINE",
    description: "",
    type: "company",
  },
  {
    id: 5,
    img: "",
    link: "https://blog.dramancompany.com/",
    title: "드라마앤컴퍼니",
    description: "",
    type: "company",
  },
  {
    id: 6,
    img: "",
    link: "https://woowabros.github.io/",
    title: "우아한형제들",
    description: "",
    type: "company",
  },
  {
    id: 7,
    img: "",
    link: "https://ko.lab.appa.pe/",
    title: "앱에이프 랩",
    description: "",
    type: "company",
  },
  {
    id: 8,
    img: "",
    link: "https://www.bsidesoft.com/",
    title: "비사이드소프트",
    description: "",
    type: "company",
  },
  {
    id: 9,
    img: "",
    link: "https://medium.com/daangn",
    title: "당근마켓",
    description: "",
    type: "company",
  },
  {
    id: 10,
    img: "",
    link: "https://velopert.com/",
    title: "velopert",
    description: "개발자 VELOPERT의 개발·일상",
    type: "private",
  },
  {
    id: 11,
    img: "",
    link: "https://velopert.com/",
    title: "벨로퍼트",
    description: "개발자 VELOPERT의 개발 블로그",
    type: "private",
  },
  {
    id: 12,
    img: "",
    link: "https://www.zerocho.com/",
    title: "제로초",
    description: "개발자 제로초의 개발 블로그",
    type: "private",
  },
  {
    id: 13,
    img: "",
    link: "https://blog.gaerae.com/",
    title: "개발자스럽다",
    description: "IT 트렌드 관련 블로그",
    type: "private",
  },
  {
    id: 14,
    img: "",
    link: "https://dev-yakuza.github.io/ko/",
    title: "야쿠자",
    description: "React Native 등 각종 개발 지식",
    type: "private",
  },
];

export const youtubeList: Item[] = [
  {
    id: 1,
    img: "",
    link: "https://www.youtube.com/channel/UCO7g158NWgLyn98z8v3zduA",
    title: "코딩하는거니",
    description: "개발 지식과 코딩 강의",
    type: "private",
  },
  {
    id: 2,
    img: "",
    link: "https://www.youtube.com/c/dongbinna/videos",
    title: "동빈나",
    description: "개발 지식과 코딩 강의",
    type: "private",
  },
  {
    id: 3,
    img: "",
    link: "https://www.youtube.com/c/ZeroChoTV/videos",
    title: "제로초",
    description: "개발 지식과 코딩 강의",
    type: "private",
  },
  {
    id: 4,
    img: "",
    link: "https://www.youtube.com/c/TeccboiWonie/videos",
    title: "코딩하는 테크보이 워니",
    description: "개발 지식과 코딩 강의",
    type: "private",
  },
  {
    id: 5,
    img: "",
    link: "https://www.youtube.com/c/노마드코더NomadCoders/videos",
    title: "노마드코더",
    description: "개발 지식과 코딩 강의",
    type: "private",
  },
  {
    id: 6,
    img: "",
    link: "https://www.youtube.com/c/드림코딩by엘리/videos",
    title: "드림코딩 by 엘리",
    description: "프론트엔드 개발자 커리어 및 강의",
    type: "private",
  },
  {
    id: 7,
    img: "",
    link: "https://www.youtube.com/channel/UCLR3sD0KB_dWpvcsrLP0aUg",
    title: "todaycode오늘코드",
    description: "데이터 분석",
    type: "private",
  },
  {
    id: 8,
    img: "",
    link: "https://www.youtube.com/channel/UCScI4bsr-RaGdYSC2QAHWug/videos",
    title: "HOWLAB",
    description: "Android 강의",
    type: "private",
  },
];

export const communityList: Item[] = [
  {
    id: 1,
    img: "",
    link: "https://okky.kr/",
    title: "OKKY",
    description: "개발자 커뮤니티",
    type: "private",
  },
  {
    id: 2,
    img: "",
    link: "https://stackoverflow.com/",
    title: "스택오버플로우",
    description: "세계적인 개발 커뮤니티",
    type: "private",
  },
  {
    id: 3,
    img: "",
    link: "https://reactnativeseoul.org/",
    title: "리액트네이티브서울",
    description: "한국 리액트네이티브 커뮤니티",
    type: "private",
  },
];
